name: dependaboja

on:
  push:
    branches:
      - master
  pull_request:
    branches: [deps/**]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependaboja:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0
      - name: Dependaboja
        uses: evoja/dependaboja@v.0/0.2
        with:
          sync_with: master
